### PR TITLE
Added additional clarification in security section

### PR DESCRIPTION
**Pull request by cabanier**
***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr-hand-input/pull/87.html" title="Last updated on Mar 2, 2021, 8:04 PM UTC (b5c9837)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr-hand-input/87/a365247...cabanier:b5c9837.html" title="Last updated on Mar 2, 2021, 8:04 PM UTC (b5c9837)">Diff</a>

### CODE REVIEW

**Comment by Manishearth** [comment]
A more thorough exploration of what "noising" and "rounding" means would be good to have, but this is a good start!

**Comment by cabanier** [comment]
Thank you but I didn't want to pull it in just yet :-)
I wanted our security people to take a look first.

**Comment by cabanier** [comment]
No big deal though. If they want changes, I will create another PR.

**Comment by Manishearth** [comment]
Oh yeah absolutely, no rush.  Having just these changes is quite good already!

**Pull request merged**
