### PR TITLE
Allow caching of XRJointPoses

### LINKED ISSUE #28: `getJointPose` should return a cached value
We made some changes to the WebXR spec to limit the number of new objects we created.
We should do the same for `getJointPose`

### PR DESCRIPTION
**Pull request by cabanier**
Closes #28

***
<a href="https://pr-preview.s3.amazonaws.com/cabanier/webxr-hand-input/pull/32.html" title="Last updated on Jul 24, 2020, 9:18 PM UTC (3ca0497)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr-hand-input/32/cb7e1d6...cabanier:3ca0497.html" title="Last updated on Jul 24, 2020, 9:18 PM UTC (3ca0497)">Diff</a>

### CODE REVIEW

**Comment by Manishearth** [comment]
I'm going to agenda this because this might be surprising for some, but also it's a new API so we may be able to sufficiently document this.

The original tradeoffs with caching poses were:

 - People already have written code (not applicable here)
 - People may wish to hold on to old pose objects to remember where something was.

The latter one is what concerns me.

/agenda to check if folks are okay with poses being cached in this case only

**Comment by Manishearth** [comment]
@cabanier I wonder: we probably should specify what this means for the XRRigidTransform and the DOMPointReadOnlys that live on the XRJointPose. I assume that's cached as well? The way "populate the pose" is currently written your changes would make this possible, but we should probably call it out specifically, maybe with an inline note.

**Comment by cabanier** [comment]
Yes, we should say that the all the members are cached too.

**Comment by cabanier** [comment]
@Manishearth so it seems people preferred a solution where we get the poses in bulk and add caching behavior to that.
Should I close this PR for now?

**Comment by Manishearth** [comment]
@cabanier sure, i'm right now writing up the issue :smile:

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr-hand-input/issues/37

**Pull request closed without merging**
